### PR TITLE
Added reduction monte carlo

### PR DESCRIPTION
**Pull request by elevien**
Playing around with ReductionMonteCarloSimulation Type and dispatch for monte_carlo_simulation. prob_func is now a keyword argument.

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
Does it need to be a separate function? I think the original `MonteCarloSimulation` could be modified to have the fieldname changed to `solution_data`, and have an argument for `output_func(sol)`. I don't think there's a need to make it only work on `last(sol)`, since the user can turn off all intermediate saving by passing `save_timeseries=false` (since the splatted kwargs are sent to the solver). That would get better performance than creating a full solver and then discarding all but the last point anyways, and would make the `output_func` more general.

As for making `prob_func` a kwarg: did you check the `@code_warntype` to see if there's any type-stability issues? You always have to be careful about changing the type of the argument in a keyword argument because kwargs don't dispatch (at least until https://github.com/JuliaLang/julia/pull/16580 gets merged). I think it may be okay here, but I think it should be checked for stability and whether there's a performance hit first.

If `prob_func` is fine as a keyword argument performance-wise, then it all could collapse back into one function with `output_func=identity` as a kwarg.

**Comment by ChrisRackauckas** [comment]
Also, you need to make sure you update the tests when you make changes. The CI tests are failing because it's still using `prob_func` as an optional arg in the 4th test.

**Comment by elevien** [comment]
Ok thanks. Do you mean get rid of `ReductionMonteCarloSimulation`, or just the dispatch of `monte_carlo_simulation`?  When running `monte_carlo_simulation` with `output_func`, it would be nice if one could run simulations until the sample standard deviation is below some desired tolerance. Does it makes sense to implement this within `pmap`?

**Comment by ChrisRackauckas** [comment]
Thanks!

**Pull request merged**
