### PR TITLE
Reduction and batching

### PR DESCRIPTION
**Pull request by elevien**
Hi, I've added something called `end_condition`. When this evaluates to true the simulations are terminated. I only implemented it when `parallel_type == :none` because I'm not really sure how this should work for parallel simulations.  I also added something called `start_check` that indicates how many simulations to do before checking `end_condition`. This is just a few lines of code so if you have other plans that will render this obsolete that is fine.

### CODE REVIEW

**Comment by elevien** [comment]
Maybe I should get rid of `start_check` and have `end_condition` depend on `i`? That would make using `end_condition` more like `prob_func` and `output_func`.

**Comment by ChrisRackauckas** [comment]
Sorry, I didn't forget about this. We should try to find out how to get this working with parallelism through some form of batching or reduction. May need to ask around.

**Comment by elevien** [comment]
> Sorry, I didn't forget about this. We should try to find out how to get this working with parallelism through some form of batching or reduction. May need to ask around.

I realized I should have waited for 2.0 anyways. I can fix this up now but I may need help handeling parallelism though. Any ideas? I haven't been able to find much on this.

**Comment by ChrisRackauckas** [comment]
I actually have no idea how to make this work with parallelism...

**Comment by ChrisRackauckas** [comment]
Oh, we can batch it. Instead of solving all of them "in one batch", we can apply a batch, then check end condition, then apply another batch. We can default something like, `batch_size = num_monte/10`. So then if `num_monte = 2000`, it will solve 200, check the end condition, solve another 200, etc. This would give it a way to end quicker (I assume you're doing something like, end when the variance is is low enough or something like that?). This same logic can apply to each form of parallelism, and non-parallel.

Going all the way, we can mix reductions and end conditions. Best explained by design + example. The design would be:

```julia
reduction(u,batch,I) 
end
# u is the reduction value
# batch is the current value
# I is the range of current i's
# Return is the new u, and a boolean for termination
```

The standard case would be the following:

```julia
reduction(u,batch,I) 
  append(u,batch),false
end
```

Which would mean "take what we just computed, append it to the array of saves, and continue". Note that we would also need to take in a type for starting `u`, with the default `u=[]`.

Just for examples, let's say you wanted to do a really long computation, just to compute the mean. Then instead you can just compute a sum. Instead of getting any arrays out, you can just reduce the sum each batch, like:

```julia
reduction(u,batch,I) 
  u+sum(batch),false
end
```

so then the final result would return just the single value which is the sum, instead of the array of `output_func(sol)`. This could drastically reduce the memory. And then you can have returning true cause it to halt.

**Comment by elevien** [comment]
>  So then if num_monte = 2000, it will solve 200, check the end condition, solve another 200, etc. This would give it a way to end quicker

When using parallelism, is the idea to solve each batch in parallel, or within the parallel loops break things into batches? I think breaking stuff into batches within the parallel loops would be faster, but I'm not really sure how to implement it. For example, is it safe/possible to break from the parallel loops like `pmap`? Also `solution_data` would have to be some sort of shared array, right?

**Comment by ChrisRackauckas** [comment]
>I think breaking stuff into batches within the parallel loops would be faster, but I'm not really sure how to implement it. For example, is it safe/possible to break from the parallel loops like pmap? Also solution_data would have to be some sort of shared array, right?

`pmap` already can do internal batching with one of its keyword arguments. But that's not we're looking for. We need a way to short-circuit. To do that, we require a sync, unless we want to build an asynchronous architecture with the master worker on a green thread reading from a shared data structure calling kill commands, but that's fragile. It's not even necessarily faster because of the within-batch data transfers. You'd have to batch those if you don't want too much overhead, and that's when we start going overboard with problems. This also doesn't solve the reductions problem. Parallel reductions from online sources is a very difficult problem. We can't really use Spark or Hadoop here, so we'd probably go to HPAT.jl, but yes, this is completely overengineering. Building something to do this is an entire project itself.

No, the better idea is to solve each batch in parallel. 20_000 trajectories, cut it up into batches of 2_000 trajectories, but if the reduction returns true then short-circuit and end. The standard way, which would have zero overhead, is just 1 batch of 20_000 trajectories. The user could cut it to smaller batches for doing reductions and short-circuiting. 

This is easy to implement and fairly efficient unless the batch size is large. Realistically, `pmap` using the Inifiniband over TCP is actually very low overhead for what we're doing because we have a trivial (almost non-existent) data transfer. Actually, if we remove the closure definition from the `pmap` and instead just make a straight function call to a function pre-defined in the DiffEqMonteCarlo, there is essentially zero data transfer (there's a message pass for an integer and a start). This is then something on the order of seconds (on the high end. It actually depends on network architecture and should be lower if the topology is any good). So as long as the batches take tens of seconds to run, the overhead by batching is essentially zero.

That's for `pmap`. But if someone is running batches that takes anything quicker than that, most likely they should be using threading, which seems to currently have a start time in the hundreds of nanoseconds to milliseconds (which is why it's okay for quick broadcasted calls). So again, we're still in the clear as long as the user isn't batching runs to take 10's of milliseconds. But at that point, shouldn't you be running serial? At which point, we're optimal.

So I think this should be perfectly fine. The biggest thing is just making sure the reduction tools work with the current analysis tools so it's easy to do things like short-circuit when the SEM is sufficiently small.

**Comment by ChrisRackauckas** [comment]
The only case where we would really lose out here is for uneven length runs. This can happen with adaptive timestepping, but I don't have a good solution for it at all, other than dynamic process killing which again is very fragile.

**Comment by elevien** [comment]
> Parallel reductions from online sources is a very difficult problem. We can't really use Spark or Hadoop here, so we'd probably go to HPAT.jl, but yes, this is completely overengineering. Building something to do this is an entire project itself.

I'm not really sure what all this means, but it seems like it isn't so relevant? I need to learn more about parallel computing. 

> No, the better idea is to solve each batch in parallel. 20_000 trajectories, cut it up into batches of 2_000 trajectories, but if the reduction returns true then short-circuit and end. The standard way, which would have zero overhead, is just 1 batch of 20_000 trajectories. The user could cut it to smaller batches for doing reductions and short-circuiting.

Ok, I gave this a try. Once this is all good we should move `reduction `, `batch_size` and `u_init` to DiffEqBase, right? It seems like those should be attached to the problem.

**Comment by elevien** [comment]
Note that I moved `elapsedTime` around. I'm not sure if you want to include the overhead from setting up the parallel simulations.

**Comment by ChrisRackauckas** [comment]
>Note that I moved elapsedTime around. I'm not sure if you want to include the overhead from setting up the parallel simulations.

Sounds good. I'm not sure if it's really necessary anyways. That's a relic from ancient times.

**Comment by elevien** [comment]
Thanks for finishing this up!

**Pull request merged**
